### ISSUE TITLE
Something wrong with regex pattern

### ISSUE THREAD

**Issue by reatlat** [sromexs/get-sitemap-links#1]
Regex rules may miss-match sometimes
for example code below may find next url `https://www.orangemarketing.com</loc><lastmod>2023-01-30</lastmod></url><url><loc>https://www.orangemarketing.com/555`

Its contains part of XML sitemap, looks like issue with missing trailing slash

```js
const GetSitemapLinks = require("get-sitemap-links").default;

(async () => {
  const array = await GetSitemapLinks(
    "https://www.orangemarketing.com/sitemap.xml"
  );
  
  console.table(array);
})();

```

**Comment by sromexs** [comment]
Thank you for bringing this to our attention. We have reviewed the issue and made some improvements to the regex used to parse the sitemap links. We recommend upgrading to the latest version of the app to ensure that this issue is resolved. Please let us know if you encounter any further issues. Thank you for using Get Sitemap Links!

**Comment by reatlat** [comment]
@sromexs that was quick!
Thank you so much, and have a great weekend 🎉
